world-event: ss
item-event:
  - DIAMOND
  - IRON
  - GOLD
  - NETHERITE
custom-model-data-chest:
item-chest: CHEST

rewards:
  epica:
    command: "/crate key give %player% epica 1"
  comune:
    command: "/crate key give %player% comune 3"

coordinates:
  coordinata 1:
    x: 39
    y: 67
    z: 25
  coordinata 2:
    x: 22
    y: 67
    z: 46
  coordinata 3:
    x: -24
    y: 67
    z: 20
  coordinata 4:
    x: -75
    y: 67
    z: 18
  coordinata 5:
    x: -75
    y: 67
    z: 53
  coordinata 6:
    x: -27
    y: 63
    z: 66
  coordinata 7:
    x: 0
    y: 67
    z: 60
  coordinata 8:
    x: 66
    y: 68
    z: 26
  coordinata 9:
    x: 90
    y: 68
    z: 44
  coordinata 10:
    x: 51
    y: 67
    z: 49
  coordinata 11:
    x: 30
    y: 66
    z: 70
  coordinata 12:
    x: -1
    y: 67
    z: 11
  coordinata 13:
    x: -24
    y: 64
    z: -1
  coordinata 14:
    x: 26
    y: 66
    z: -3
  coordinata 15:
    x: 39
    y: 66
    z: -53
